apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-example

commonLabels:
  app: postgres

resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml

configMapGenerator:
  - name: postgres-internal-cnf
    envs:
      - postgres.env

  - name: postgres-init-scripts
    files:
      - create-dominion-db.sql
